"""
AI Security -- ML Domain Risk Scorer (Inference)
===================================================
Loads the trained domain_risk_model.joblib and scores how "suspicious"
a domain string looks (DGA / phishing-pattern detection).

This is used to PRIORITIZE alerts generated by the zero-trust policy
engine (ai_policy.py) -- it does NOT make the allow/block decision
itself. The firewall policy remains deterministic.

If the model file doesn't exist yet, run train_model.py first.
"""

import os
import joblib

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "domain_risk_model.joblib")

_model = None


def _load_model():
    global _model
    if _model is None:
        if not os.path.exists(MODEL_PATH):
            return None
        _model = joblib.load(MODEL_PATH)
    return _model


def score_domain(domain):
    """
    Returns a dict:
      {
        "ml_available": bool,
        "ml_risk_score": float (0.0-1.0),   # probability domain looks suspicious
        "ml_label": "benign" | "suspicious",
        "ml_severity": "info" | "warn" | "danger"
      }

    If the model hasn't been trained yet, returns ml_available=False
    with a neutral score so callers can degrade gracefully.
    """
    model = _load_model()
    domain = domain.lower().strip().rstrip(".")

    if model is None:
        return {
            "ml_available": False,
            "ml_risk_score": 0.0,
            "ml_label": "unknown",
            "ml_severity": "info",
        }

    proba = model.predict_proba([domain])[0]
    risk_score = float(proba[1])  # P(class=1=suspicious)

    if risk_score >= 0.6:
        severity = "danger"
        label = "suspicious"
    elif risk_score >= 0.35:
        severity = "warn"
        label = "suspicious"
    else:
        severity = "info"
        label = "benign"

    return {
        "ml_available": True,
        "ml_risk_score": round(risk_score, 3),
        "ml_label": label,
        "ml_severity": severity,
    }


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        print(score_domain(sys.argv[1]))
    else:
        for d in ["facebook.com", "xk29fj3kqz.tk", "paypal-secure-verify.info", "github.com"]:
            print(d, "->", score_domain(d))
